[build.environment]
PUBLIC_SUPABASE_URL = "https://gvowfbrpmotcfxf.supabase.co"
PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2b3dmYnJwbW90Y2Z4Znp6aHhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzMTc0NjksImV4cCI6MjA1NTg5MzQ2OX0.CceIKEQr3NYuEZ76mjuFVYRCG_X5lTP8MEQ-4paIoTs"