version: 2
services:
  - type: web
    name: buy-box-render-service
    env: node
    buildCommand: npm install
    startCommand: node render-service/server.js
    healthCheckPath: /health
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
