<script lang="ts">
	import {
		Section,
		Container,
		Text,
		Heading,
		Hr,
		Html,
		Head,
		Preview,
		Body,
		Link
	} from 'better-svelte-email';

	export let date: string;
	export let totalOrders: number;
	export let totalRevenue: string;
	export let topSku: { sku: string; title: string; profit: string };
	export let orders: any[]; // Simplified for the list

	// Helper to get profit color
	const getProfitColor = (val: string) => (val.includes('-') ? 'red' : 'green');
</script>

<Html>
	<Head />
	<Preview preview="Amazon Daily Report for {date}" />
	<Body style="background-color: #f6f9fc; font-family: -apple-system, sans-serif;">
		<Container
			style="background-color: #ffffff; margin: 0 auto; padding: 20px 0 48px; margin-bottom: 64px;"
		>
			<Section style="padding: 0 48px;">
				<Heading style="font-size: 24px; color: #333;">Amazon Daily Report</Heading>
				<Text style="font-size: 16px; color: #555;">
					Summary for <strong>{date}</strong>
				</Text>

				<Section
					style="background-color: #f0f7ff; padding: 20px; border-radius: 5px; margin: 20px 0;"
				>
					<Text style="margin: 0; font-size: 18px;">Orders: <strong>{totalOrders}</strong></Text>
					<Text style="margin: 10px 0 0; font-size: 18px;"
						>Revenue: <strong>{totalRevenue}</strong></Text
					>
				</Section>

				<Hr style="border-color: #e6ebf1; margin: 20px 0;" />

				<Heading as="h2" style="font-size: 18px; color: #333;">Top Performer</Heading>
				<Text style="font-size: 14px; margin-bottom: 5px;">
					<Link
						href={`https://operations.chefstorecookbook.com/dashboard/amazon/orders/sku/${topSku.sku}`}
						>{topSku.sku}</Link
					>
				</Text>
				<Text style="font-size: 14px; color: #666; margin-top: 0;">{topSku.title}</Text>
				<Text style={`font-weight: bold; color: ${getProfitColor(topSku.profit)}`}
					>Profit: {topSku.profit}</Text
				>

				<Hr style="border-color: #e6ebf1; margin: 20px 0;" />

				<Heading as="h2" style="font-size: 18px; color: #333;">Order Highlights</Heading>
				{#each orders.slice(0, 10) as order}
					<Section style="border-bottom: 1px solid #eee; padding: 10px 0;">
						<Text style="margin:0; font-size: 14px;">
							<Link
								href={`https://sellercentral.amazon.co.uk/orders-v3/order/${order.amazon_order_id}`}
								>{order.amazon_order_id}</Link
							>
						</Text>
						<Text style="margin: 5px 0 0; font-size: 12px; color: #777;">
							Rev: {order.revenue} | Cost: {order.cost} |
							<span style={`font-weight:bold; color: ${getProfitColor(order.profit)}`}
								>Profit: {order.profit}</span
							>
						</Text>
					</Section>
				{/each}

				<Text style="font-size: 12px; color: #8898aa; margin-top: 30px; text-align: center;">
					Generated by Parkers Dashboard Automation
				</Text>
			</Section>
		</Container>
	</Body>
</Html>
